### ISSUE TITLE
Quickstart guide

### ISSUE THREAD

**Issue by emschwartz** [autometrics-dev/autometrics-go#45]
There is a fair amount of content in the readme. Someone that was integrating the Rust library commented that it would be useful to have a clear quickstart guide for anyone that doesn't need to be convinced about the project but just wants to follow a set of steps to add it. [This](https://github.com/autometrics-dev/autometrics-rs#quickstart) is what we added for the Rust library

**Comment by Suraj-kumar00** [comment]
Hi Evan, How's it going?
My name is Suraj, currently I'm working on my frontend skills and really interested to contribute in your projects, I'm new to open-source could you please let me know any sort of guidance so that I can contribute to this issue?

**Comment by gagbo** [comment]
Hello,

Evan's not working with us anymore, but either way, I'm mostly the one responsible for the Go version of the autometrics library. I kind of forgot about closing this issue after I made an extra pass on the README already, from useful feedback from early adopters/testers.

If you feel like the documentation here and on [autometrics.dev](https://docs.autometrics.dev/go/quickstart) is not enough, can you tell me what's missing according to you? Knowing what's missing in the documentation is a good first step to try to make it better :)

**Comment by gagbo** [comment]
The [new `am instrument` sub command](https://github.com/autometrics-dev/am/releases/tag/v0.6.0) can do a lot of work now, and a `grep` version of the quickstart has also been added in the README of autometrics
